<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="PipeSplit" Description="Split pipe by points and lengths" ID="bf46c1ae-415e-419e-b368-77400712c8c6" Category="MEPDesign">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="57a06297-60f4-4877-90a8-073da464ab17" type="PythonNodeModels.PythonNode" nickname="Python Script" x="434" y="258" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script># Load the Python Standard and DesignScript Libraries
import sys
import clr

# Enable Python support and load DesignScript libraryimport clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import*
 
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')
# import document manager
from RevitServices.Persistence import DocumentManager
# import transaction manager
from RevitServices.Transactions import TransactionManager
# instantiate current document
doc = DocumentManager.Instance.CurrentDBDocument
from Autodesk.Revit.DB.Plumbing.PlumbingUtils import BreakCurve 
from Autodesk.Revit.DB import XYZ

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
from Revit import GeometryConversion as gp
# The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
 
#Get pipes and unwrap
pipes = UnwrapElement(IN[0])
points = IN[1]
distancias = IN[2]



# start transaction

TransactionManager.Instance.EnsureInTransaction(doc)

for t in range(0,len(pipes),1):
	for i in range(0,len(points[t]),1):
	
		if(distancias[t][i]&gt;=0.1):
			
			dbPoint = points[t][i].ToXyz()
			pipe = pipes[t]
			newPipeId = BreakCurve(doc, pipe.Id, dbPoint)
			newPipe = doc.GetElement(newPipeId)	
			
			
			newPipeConnectors = newPipe.ConnectorManager.Connectors
			connA = None
			connB = None
			for c in pipe.ConnectorManager.Connectors:
				pc = c.Origin
				nearest = [x for x in newPipeConnectors if pc.DistanceTo(x.Origin) &lt; 0.01]
				if nearest:
					connA = c
					connB = nearest[0]
			takeoff = doc.Create.NewUnionFitting(connA, connB)
			
		
TransactionManager.Instance.TransactionTaskDone()

OUT = 0
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="151c56a8-86bc-48e3-9a6c-f646d29f7e86" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="264" y="204" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7f48fc75-a83e-46a1-8200-97fded9c2d8c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="263" y="294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c51cdec4-8732-4766-ae17-b8756c3b04ca" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="260" y="397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Lengths" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="151c56a8-86bc-48e3-9a6c-f646d29f7e86" start_index="0" end="57a06297-60f4-4877-90a8-073da464ab17" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7f48fc75-a83e-46a1-8200-97fded9c2d8c" start_index="0" end="57a06297-60f4-4877-90a8-073da464ab17" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c51cdec4-8732-4766-ae17-b8756c3b04ca" start_index="0" end="57a06297-60f4-4877-90a8-073da464ab17" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>